//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace httpget {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?Function=PreviewInput&Input=1")]
        public string Button1 {
            get {
                return ((string)(this["Button1"]));
            }
            set {
                this["Button1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?Function=PreviewInput&Input=2")]
        public string Button2 {
            get {
                return ((string)(this["Button2"]));
            }
            set {
                this["Button2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?Function=PreviewInput&Input=3")]
        public string Button3 {
            get {
                return ((string)(this["Button3"]));
            }
            set {
                this["Button3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?Function=PreviewInput&Input=4")]
        public string Button4 {
            get {
                return ((string)(this["Button4"]));
            }
            set {
                this["Button4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?Function=FadeToBlack")]
        public string Button5 {
            get {
                return ((string)(this["Button5"]));
            }
            set {
                this["Button5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?Function=QuickPlay&Input=1")]
        public string Long1 {
            get {
                return ((string)(this["Long1"]));
            }
            set {
                this["Long1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?Function=QuickPlay&Input=2")]
        public string Long2 {
            get {
                return ((string)(this["Long2"]));
            }
            set {
                this["Long2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?Function=QuickPlay&Input=3")]
        public string Long3 {
            get {
                return ((string)(this["Long3"]));
            }
            set {
                this["Long3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?Function=QuickPlay&Input=4")]
        public string Long4 {
            get {
                return ((string)(this["Long4"]));
            }
            set {
                this["Long4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("muted;?Function=MasterAudioOn;?Function=MasterAudioOff")]
        public string Long5 {
            get {
                return ((string)(this["Long5"]));
            }
            set {
                this["Long5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string LongPressInterval {
            get {
                return ((string)(this["LongPressInterval"]));
            }
            set {
                this["LongPressInterval"] = value;
            }
        }
    }
}
